# Generated by Django 4.2.9 on 2024-01-06 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('skill', models.IntegerField()),
                ('league_titles', models.IntegerField(default=0)),
                ('cup_titles', models.IntegerField(default=0)),
                ('ucl', models.IntegerField(default=0)),
                ('uel', models.IntegerField(default=0)),
                ('uecl', models.IntegerField(default=0)),
                ('europe', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralTeam',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='football_simulation_app.team')),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=255)),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_simulation_app.team')),
            ],
        ),
    ]
