# Generated by Django 4.2.9 on 2024-01-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_simulation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
