# Generated by Django 4.2.9 on 2024-01-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_simulation_app', '0002_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ucl_places', models.IntegerField(default=0)),
                ('uel_places', models.IntegerField(default=0)),
                ('uecl_places', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_simulation_app.country'),
        ),
    ]
