# Generated by Django 4.2.9 on 2024-01-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_simulation_app', '0003_country_alter_team_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueteam',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.DeleteModel(
            name='GeneralTeam',
        ),
        migrations.DeleteModel(
            name='LeagueTeam',
        ),
    ]
