# Generated by Django 4.2.9 on 2024-01-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_simulation_app', '0005_alter_team_logo_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='CAM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='CB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='CDM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='CM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='GK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='LB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='LM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='LW',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='RB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='RM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='RW',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ST',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='WLB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='WRB',
            field=models.IntegerField(default=0),
        ),
    ]
