# Generated by Django 4.2.9 on 2024-01-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_simulation_app', '0007_team_attack_skill_team_defense_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='attack_skill',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='defense_skill',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='midfield_skill',
            field=models.FloatField(default=0, null=True),
        ),
    ]
