# Generated by Django 4.2.9 on 2024-01-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_simulation_app', '0008_alter_team_attack_skill_alter_team_defense_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
