# Generated by Django 4.2.9 on 2024-01-09 18:39

from django.db import migrations, models
import football_simulation_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('football_simulation_app', '0009_alter_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='main_positions',
            new_name='main_position',
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=football_simulation_app.models.player_photo_path),
        ),
    ]
