# Generated by Django 4.2.9 on 2024-01-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_simulation_app', '0011_country_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('apps', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_simulation_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_simulation_app.team')),
            ],
        ),
    ]
