# Generated by Django 4.2.9 on 2024-02-29 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football_simulation_app', '0012_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_simulation_app.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
