# Generated by Django 4.2.9 on 2024-02-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_simulation_app', '0013_userselectedteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselectedteam',
            name='selected_team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='football_simulation_app.team'),
        ),
    ]
