# Teams
# Name, Skill
ENG_TEAMS = [("Arsenal", 95),
             ("Aston Villa", 75),
             ("Bournemouth", 65),
             ("Brentford", 70),
             ("Brighton", 80),
             ("Burnley", 65),
             ("Chelsea", 90),
             ("Crystal Palace", 70),
             ("Everton", 70),
             ("Fulham", 70),
             ("Liverpool", 100),
             ("Luton", 55),
             ("Manchester City", 100),
             ("Manchester United", 90),
             ("Newcastle United", 90),
             ("Nottingham Forest", 70),
             ("Sheffield United", 65),
             ("Tottenham Hotspur", 90),
             ("West Ham United", 75),
             ("Wolverhampton Wanderers", 70)]

ESP_TEAMS = [("Alaves", 65),
             ("Almeria", 70),
             ("Athletic Bilbao", 80),
             ("Atletico Madrid", 90),
             ("Barcelona", 95),
             ("Cadiz", 70),
             ("Celta Vigo", 75),
             ("Getafe", 70),
             ("Girona", 75),
             ("Granada", 65),
             ("Las Palmas", 65),
             ("Mallorca", 75),
             ("Osasuna", 75),
             ("Rayo Vallecano", 75),
             ("Real Betis", 80),
             ("Real Madrid", 100),
             ("Real Sociedad", 85),
             ("Sevilla", 85),
             ("Valencia", 80),
             ("Villareal", 80)]

GER_TEAMS = [("FC Augsburg", 70),
             ("Union Berlin", 80),
             ("VfL Bochum", 70),
             ("Werder Bremen", 70),
             ("Darmstadt 98", 65),
             ("Borussia Dortmund", 95),
             ("Eintracht Frankfurt", 85),
             ("SC Freiburg", 80),
             ("1. FC Heidenheim", 65),
             ("1899 Hoffenheim", 70),
             ("1. FC Koln", 70),
             ("RB Leipzig", 90),
             ("Bayer Leverkusen", 85),
             ("Mainz 05", 75),
             ("Borussia Monchengladbach", 75),
             ("Bayern Munchen", 100),
             ("VfB Stuttgart", 70),
             ("VfL Wolfsburg", 75)]

ITA_TEAMS = [("AC Milan", 90),
             ("AS Roma", 85),
             ("Atalanta", 85),
             ("Bologna", 75),
             ("Cagliari", 65),
             ("Empoli", 70),
             ("Fiorentina", 80),
             ("Frosinone", 65),
             ("Genoa", 65),
             ("Hellas Verona", 65),
             ("Inter Milan", 90),
             ("Juventus", 90),
             ("Lazio", 85),
             ("Lecce", 70),
             ("Monza", 75),
             ("Napoli", 90),
             ("Salernitana", 70),
             ("Sassuolo", 70),
             ("Torino", 75),
             ("Udinese", 70)]

FRA_TEAMS = [("Brest", 70),
             ("Clermont", 70),
             ("Le Havre", 65),
             ("RC Lens", 85),
             ("Lille", 80),
             ("Lorient", 70),
             ("Olympique Lyon", 80),
             ("Marseille", 80),
             ("AS Monaco", 80),
             ("Metz", 65),
             ("Montpellier", 70),
             ("Nantes", 70),
             ("Nice", 75),
             ("PSG", 100),
             ("Reims", 70),
             ("Rennes", 80),
             ("Strasbourg", 70),
             ("Toulouse", 70)]

NED_TEAMS = [("Ajax", 85),
             ("Almere City", 60),
             ("AZ", 75),
             ("Excelsior", 60),
             ("Feyenoord", 80),
             ("Fortuna Sittard", 65),
             ("Go Ahead Eagles", 65),
             ("SC Heerenveen", 70),
             ("Heracles Almelo", 60),
             ("NEC", 65),
             ("PEC Zwolle", 60),
             ("PSV Eindhoven", 80),
             ("RKC Waalwijk", 65),
             ("Sparta Rotterdam", 70),
             ("Twente", 75),
             ("Utrecht", 70),
             ("Vitesse", 65),
             ("Volendam", 60)
             ]

POR_TEAMS = [("Arouca", 70),
             ("Benfica", 85),
             ("Boavista", 70),
             ("Braga", 80),
             ("Casa Pia", 65),
             ("Chaves", 70),
             ("Estoril", 60),
             ("Estrela da Amadora", 60),
             ("Famalicao", 70),
             ("Farense", 60),
             ("Gil Vicente", 65),
             ("Moreirense", 60),
             ("Portimonense", 60),
             ("Porto", 85),
             ("Rio Ave", 65),
             ("Sporting CP", 80),
             ("Vitoria de Guimaraes", 75),
             ("Vizela", 65)
             ]

BEL_TEAMS = [("Anderlecht", 75),
             ("Antwerp", 75),
             ("Cercle Brugge", 70),
             ("Charleroi", 70),
             ("Club Brugge", 75),
             ("Eupen", 60),
             ("Genk", 80),
             ("Gent", 75),
             ("Kortrijk", 60),
             ("Mechelen", 60),
             ("OH Leuven", 65),
             ("RWD Molenbeek", 60),
             ("Sint-Truiden", 65),
             ("Standard Liege", 75),
             ("Union SG", 80),
             ("Westerlo", 70)]

SCO_TEAMS = [("Aberdeen", 75),
             ("Celtic", 80),
             ("Dundee", 60),
             ("Hearts", 70),
             ("Hibernian", 70),
             ("Kilmarnock", 60),
             ("Livingston", 65),
             ("Motherwell", 70),
             ("Rangers", 80),
             ("Ross County", 60),
             ("St Johnstone", 65),
             ("St Mirren", 65)]

AUS_TEAMS = [("Austria Klagenfurt", 65),
             ("Austria Lustenau", 65),
             ("Austria Wien", 70),
             ("Blau-WeiB Linz", 60),
             ("LASK", 70),
             ("Rapid Wien", 70),
             ("Red Bull Salzburg", 80),
             ("Rheindorf Altach", 60),
             ("Sturm Graz", 75),
             ("TSV Hartberg", 60),
             ("Wolfsberger AC", 65),
             ("WSG Tirol", 65)
             ]

ROM_TEAMS = [("FCSB", 75),
             ("CFR Cluj", 70),
             ("Universitatea Craiova", 65),
             ("Farul Constanta", 65),
             ("Sepsi", 60),
             ("Rapid Bucuresti", 65),
             ("Dinamo Bucuresti", 65),
             ("UTA Arad", 60),
             ("Otelul Galati", 60),
             ("U Cluj", 65),
             ("Petrolul Ploiesti", 60),
             ("Politehnica Iasi", 60)
            ]