# Country Teams - Name, Skill
ENG_TEAMS = [("Arsenal", 95),
             ("Aston Villa", 85),
             ("Bournemouth", 75),
             ("Brentford", 78),
             ("Brighton", 85),
             ("Burnley", 72),
             ("Chelsea", 93),
             ("Crystal Palace", 76),
             ("Everton", 74),
             ("Fulham", 77),
             ("Liverpool", 100),
             ("Luton", 68),
             ("Manchester City", 100),
             ("Manchester United", 92),
             ("Newcastle United", 88),
             ("Nottingham Forest", 75),
             ("Sheffield United", 70),
             ("Tottenham Hotspur", 90),
             ("West Ham United", 78),
             ("Wolverhampton Wanderers", 76),
             ("Leeds United", 73),
             ("Leicester City", 81),
             ("Southampton", 80),
             ("Watford", 70)]

ESP_TEAMS = [("Alaves", 65),
             ("Almeria", 72),
             ("Athletic Bilbao", 84),
             ("Atletico Madrid", 90),
             ("Barcelona", 95),
             ("Cadiz", 71),
             ("Celta Vigo", 78),
             ("Getafe", 75),
             ("Girona", 76),
             ("Granada", 70),
             ("Las Palmas", 68),
             ("Mallorca", 77),
             ("Osasuna", 78),
             ("Rayo Vallecano", 75),
             ("Real Betis", 85),
             ("Real Madrid", 100),
             ("Real Sociedad", 88),
             ("Sevilla", 86),
             ("Valencia", 80),
             ("Villareal", 84),
             ("Levante", 73),
             ("Espanyol", 76),
             ("Zaragoza", 74)]

GER_TEAMS = [("FC Augsburg", 73),
             ("Union Berlin", 82),
             ("VfL Bochum", 70),
             ("Werder Bremen", 74),
             ("Darmstadt 98", 67),
             ("Borussia Dortmund", 96),
             ("Eintracht Frankfurt", 86),
             ("SC Freiburg", 83),
             ("1. FC Heidenheim", 65),
             ("1899 Hoffenheim", 77),
             ("1. FC Koln", 74),
             ("RB Leipzig", 92),
             ("Bayer Leverkusen", 87),
             ("Mainz 05", 78),
             ("Borussia Monchengladbach", 79),
             ("Bayern Munchen", 100),
             ("VfB Stuttgart", 75),
             ("VfL Wolfsburg", 82),
             ("Fortuna Dusseldorf", 74),
             ("Hertha Berlin", 73),
             ("Nurnberg", 70)]

ITA_TEAMS = [("AC Milan", 92),
             ("AS Roma", 86),
             ("Atalanta", 88),
             ("Bologna", 76),
             ("Cagliari", 70),
             ("Empoli", 72),
             ("Fiorentina", 83),
             ("Frosinone", 68),
             ("Genoa", 70),
             ("Hellas Verona", 72),
             ("Inter Milan", 92),
             ("Juventus", 92),
             ("Lazio", 86),
             ("Lecce", 74),
             ("Monza", 77),
             ("Napoli", 94),
             ("Salernitana", 72),
             ("Sassuolo", 78),
             ("Torino", 80),
             ("Udinese", 74),
             ("Parma", 73),
             ("Sampdoria", 76),
             ("SPAL", 68)]

FRA_TEAMS = [("Brest", 72),
             ("Clermont", 74),
             ("Le Havre", 67),
             ("RC Lens", 87),
             ("Lille", 85),
             ("Lorient", 75),
             ("Olympique Lyon", 84),
             ("Marseille", 85),
             ("AS Monaco", 84),
             ("Metz", 70),
             ("Montpellier", 75),
             ("Nantes", 76),
             ("Nice", 79),
             ("PSG", 100),
             ("Reims", 74),
             ("Rennes", 86),
             ("Strasbourg", 77),
             ("Toulouse", 76),
             ("Auxerre", 74),
             ("Troyes", 70),
             ("Caen", 67)]

NED_TEAMS = [("Ajax", 88),
             ("Almere City", 66),
             ("AZ", 84),
             ("Excelsior", 65),
             ("Feyenoord", 87),
             ("Fortuna Sittard", 70),
             ("Go Ahead Eagles", 72),
             ("SC Heerenveen", 78),
             ("Heracles Almelo", 68),
             ("NEC", 72),
             ("PEC Zwolle", 65),
             ("PSV Eindhoven", 88),
             ("RKC Waalwijk", 70),
             ("Sparta Rotterdam", 77),
             ("Twente", 84),
             ("Utrecht", 79),
             ("Vitesse", 75),
             ("Volendam", 65),
             ("Cambuur", 66),
             ("NAC Breda", 68)]

POR_TEAMS = [("Arouca", 72),
             ("Benfica", 90),
             ("Boavista", 74),
             ("Braga", 88),
             ("Casa Pia", 68),
             ("Chaves", 72),
             ("Estoril", 65),
             ("Estrela da Amadora", 63),
             ("Famalicao", 76),
             ("Farense", 65),
             ("Gil Vicente", 73),
             ("Moreirense", 62),
             ("Portimonense", 71),
             ("Porto", 91),
             ("Rio Ave", 74),
             ("Sporting CP", 89),
             ("Vitoria de Guimaraes", 79),
             ("Vizela", 67),
             ("Academica Coimbra", 65),
             ("Belenenses", 64)]

BEL_TEAMS = [("Anderlecht", 82),
             ("Antwerp", 81),
             ("Cercle Brugge", 73),
             ("Charleroi", 75),
             ("Club Brugge", 85),
             ("Eupen", 66),
             ("Genk", 86),
             ("Gent", 82),
             ("Kortrijk", 67),
             ("Mechelen", 74),
             ("OH Leuven", 70),
             ("RWD Molenbeek", 65),
             ("Sint-Truiden", 70),
             ("Standard Liege", 81),
             ("Union SG", 84),
             ("Westerlo", 72),
             ("Lierse", 66),
             ("Lokeren", 62)]

SCO_TEAMS = [("Aberdeen", 81),
             ("Celtic", 88),
             ("Dundee", 65),
             ("Hearts", 79),
             ("Hibernian", 77),
             ("Kilmarnock", 70),
             ("Livingston", 71),
             ("Motherwell", 76),
             ("Rangers", 88),
             ("Ross County", 66),
             ("St Johnstone", 72),
             ("St Mirren", 74),
             ("Hamilton Academical", 64),
             ("Partick Thistle", 68),
             ("Queen's Park", 63),
             ("Dundee United", 74)]

AUS_TEAMS = [("Austria Klagenfurt", 71),
             ("Austria Lustenau", 66),
             ("Austria Wien", 78),
             ("Blau-WeiB Linz", 64),
             ("LASK", 82),
             ("Rapid Wien", 80),
             ("Red Bull Salzburg", 87),
             ("Rheindorf Altach", 65),
             ("Sturm Graz", 84),
             ("TSV Hartberg", 70),
             ("Wolfsberger AC", 77),
             ("WSG Tirol", 72),
             ("Admira Wacker", 65),
             ("Mattersburg", 69),
             ("Kapfenberger SV", 63),
             ("Wiener Neustadt", 66)]

ROM_TEAMS = [("FCSB", 84),
             ("CFR Cluj", 81),
             ("Universitatea Craiova", 79),
             ("Farul Constanta", 76),
             ("Sepsi", 74),
             ("Rapid Bucuresti", 75),
             ("Dinamo Bucuresti", 73),
             ("UTA Arad", 71),
             ("Otelul Galati", 69),
             ("U Cluj", 70),
             ("Petrolul Ploiesti", 67),
             ("Politehnica Iasi", 65),
             ("Chindia Targoviste", 63),
             ("FC Voluntari", 62),
             ("CS Mioveni", 61),
             ("Pandurii Targu Jiu", 60)]

SUI_TEAMS = [("Young Boys", 86),  # Buffed
             ("FC Basel", 84),  # Buffed
             ("FC Zurich", 81),  # Buffed
             ("Grasshoppers", 77),
             ("Servette", 79),  # Buffed slightly
             ("Lugano", 77),
             ("St. Gallen", 78),  # Buffed slightly
             ("Sion", 74),
             ("Lucerne", 75),
             ("Winterthur", 71),
             ("Thun", 69),
             ("Aarau", 67),
             ("FC Lausanne-Sport", 69),
             ("Wil 1900", 65),
             ("FC Vaduz", 66),
             ("Schaffhausen", 64)]



TUR_TEAMS = [("Galatasaray", 88),
             ("Fenerbahce", 87),
             ("Besiktas", 86),
             ("Trabzonspor", 83),
             ("Istanbul Basaksehir", 81),
             ("Adana Demirspor", 80),
             ("Konyaspor", 78),
             ("Sivasspor", 77),
             ("Antalyaspor", 76),
             ("Alanyaspor", 75),
             ("Kayserispor", 73),
             ("Gaziantep FK", 72),
             ("Hatayspor", 71),
             ("Giresunspor", 69),
             ("Rizespor", 70),
             ("MKE Ankaragucu", 68)]


GRE_TEAMS = [("Olympiacos", 87),  # Buffed
             ("Panathinaikos", 85),  # Buffed
             ("AEK Athens", 84),  # Buffed
             ("PAOK Thessaloniki", 82),
             ("Aris Thessaloniki", 79),
             ("OFI Crete", 76),
             ("Atromitos", 74),
             ("Volos", 72),
             ("Lamia", 69),
             ("Ionikos", 67),
             ("Asteras Tripoli", 71),
             ("Panetolikos", 69),
             ("PAS Giannina", 67),
             ("Xanthi", 63),
             ("Larissa", 61),
             ("Levadiakos", 60)]


CZE_TEAMS = [("Slavia Prague", 83),
             ("Sparta Prague", 82),
             ("Viktoria Plzen", 81),
             ("Banik Ostrava", 78),
             ("Jablonec", 76),
             ("Sigma Olomouc", 75),
             ("Slovan Liberec", 74),
             ("Mlada Boleslav", 72),
             ("Teplice", 71),
             ("Pardubice", 70),
             ("Hradec Kralove", 68),
             ("Zlin", 65),
             ("Pribram", 63),
             ("Karvina", 64),
             ("Opava", 62),
             ("Vysocina Jihlava", 59)]


POL_TEAMS = [("Legia Warsaw", 84),  # Buffed
             ("Lech Poznan", 82),
             ("Rakow Czestochowa", 81),
             ("Gornik Zabrze", 77),
             ("Slask Wroclaw", 75),
             ("Pogon Szczecin", 78),
             ("Wisla Krakow", 76),
             ("Jagiellonia Bialystok", 73),
             ("Zaglebie Lubin", 72),
             ("Cracovia", 71),
             ("Lechia Gdansk", 69),
             ("Wisla Plock", 68),
             ("Warta Poznan", 67),
             ("LKS Lodz", 65),
             ("Korona Kielce", 64),
             ("Podbeskidzie", 62)]


RUS_TEAMS = [("Zenit Saint Petersburg", 88),  # Buffed slightly
             ("CSKA Moscow", 86),  # Buffed slightly
             ("Spartak Moscow", 85),  # Buffed slightly
             ("Lokomotiv Moscow", 83),  # Buffed slightly
             ("Dynamo Moscow", 81),
             ("Krasnodar", 80),
             ("Rostov", 78),
             ("Rubin Kazan", 76),
             ("Ural Yekaterinburg", 74),
             ("Krylia Sovetov", 72),
             ("Akhmat Grozny", 71),
             ("Arsenal Tula", 67),
             ("Tambov", 63),
             ("Orenburg", 65),
             ("Tom Tomsk", 61),
             ("FC Nizhny Novgorod", 60)]


UKR_TEAMS = [("Shakhtar Donetsk", 88),  # Balanced
             ("Dynamo Kyiv", 86),  # Balanced
             ("Zorya Luhansk", 83),
             ("Dnipro-1", 81),
             ("Kolos Kovalivka", 78),
             ("Vorskla Poltava", 77),
             ("Metalist Kharkiv", 75),
             ("Chornomorets Odesa", 74),
             ("Karpaty Lviv", 72),
             ("Oleksandriya", 76),
             ("Lviv", 69),
             ("Veres Rivne", 68),
             ("Ingulec Petrove", 66),
             ("Kryvbas Kryvyi Rih", 65),
             ("Obolon Kyiv", 64),
             ("Prytula Kolomyya", 62)]


SRB_TEAMS = [("Red Star Belgrade", 88),  # Balanced
             ("Partizan Belgrade", 86),  # Balanced
             ("Vojvodina", 83),
             ("Cukaricki", 81),
             ("Radnicki Nis", 78),
             ("TSC Backa Topola", 77),
             ("Spartak Subotica", 74),
             ("FK Napredak", 73),
             ("FK Vozdovac", 72),
             ("FK Novi Pazar", 70),
             ("Javor Ivanjica", 68),
             ("Rad Beograd", 67),
             ("Metalac Gornji Milanovac", 66),
             ("Proleter Novi Sad", 65),
             ("Sloboda Uzice", 64),
             ("FK Kolubara", 62)]



NOR_TEAMS = [("Rosenborg", 83),
             ("Molde", 82),
             ("Bodø/Glimt", 81),
             ("Vålerenga", 76),
             ("Lillestrøm", 74),
             ("Stabæk", 71),
             ("Tromsø", 72),
             ("Viking", 78),  # Kept Viking stronger
             ("Sarpsborg 08", 73),
             ("Odd", 71),
             ("Strømsgodset", 70),
             ("Start", 68),
             ("Sandefjord", 67),
             ("Mjøndalen", 65),
             ("Kristiansund", 69),
             ("HamKam", 64)]


SWE_TEAMS = [("Malmö FF", 83),
             ("AIK", 82),
             ("Djurgården", 80),
             ("IFK Göteborg", 79),
             ("Hammarby", 78),
             ("Elfsborg", 77),
             ("Kalmar FF", 75),
             ("Sirius", 72),
             ("Helsingborg", 70),
             ("Örebro SK", 68),
             ("Norrköping", 76),
             ("Östersunds FK", 66),
             ("Brommapojkarna", 64),
             ("Degerfors", 65),
             ("Varbergs BoIS FC", 64),
             ("Trelleborgs FF", 63)]


DEN_TEAMS = [("FC Copenhagen", 86),
             ("FC Midtjylland", 84),
             ("Brøndby IF", 83),
             ("Aalborg BK", 76),
             ("Aarhus GF", 74),
             ("Odense BK", 73),
             ("Silkeborg", 71),
             ("Randers FC", 73),
             ("Horsens", 69),
             ("Lyngby", 67),
             ("Esbjerg", 65),
             ("Nordsjælland", 78),
             ("Hvidovre IF", 63),
             ("Vejle BK", 66),
             ("SønderjyskE", 70),
             ("Viborg FF", 72)]


HUN_TEAMS = [("Ferencváros", 84),
             ("MOL Fehérvár FC", 76),
             ("Újpest FC", 72),
             ("Debrecen", 70),
             ("Puskás Akadémia FC", 74),
             ("Kisvárda", 68),
             ("MTK Budapest", 67),
             ("Zalaegerszegi TE", 64),
             ("Pécsi MFC", 63),
             ("Gyirmót SE", 62),
             ("Mezőkövesd", 66),
             ("Honvéd Budapest", 71),
             ("Szeged 2011", 61),
             ("Békéscsaba 1912", 60),
             ("Haladás VSE", 65),
             ("Diósgyőri VTK", 69)]

CRO_TEAMS = [("Dinamo Zagreb", 86),
             ("Hajduk Split", 84),
             ("Rijeka", 81),
             ("Osijek", 79),
             ("Slaven Belupo", 74),
             ("Lokomotiva Zagreb", 73),
             ("Istra 1961", 70),
             ("Šibenik", 67),
             ("NK Gorica", 72),
             ("Varazdin", 69),
             ("NK Rudeš", 65),
             ("Inter Zaprešić", 63),
             ("Cibalia Vinkovci", 61),
             ("NK Hrvatski Dragovoljac", 62),
             ("NK Zadar", 60),
             ("Vinogradar", 59)]

BUL_TEAMS = [("Ludogorets", 85),
             ("CSKA Sofia", 82),
             ("Levski Sofia", 80),
             ("Slavia Sofia", 76),
             ("Botev Plovdiv", 74),
             ("Lokomotiv Plovdiv", 75),
             ("Arda Kardzhali", 71),
             ("Cherno More", 72),
             ("Beroe", 70),
             ("Pirin Blagoevgrad", 66),
             ("Septemvri Sofia", 64),
             ("Etar Veliko Tarnovo", 65),
             ("Montana", 62),
             ("Ludogorets II", 60),
             ("Minyor Pernik", 59),
             ("Dobrudzha Dobrich", 58)]


SVK_TEAMS = [("Slovan Bratislava", 84),
             ("Spartak Trnava", 81),
             ("Zilina", 80),
             ("AS Trenčín", 76),
             ("DAC Dunajská Streda", 78),
             ("Tatran Prešov", 71),
             ("Ružomberok", 74),
             ("FK Pohronie", 66),
             ("Senica", 64),
             ("Zemplín Michalovce", 69),
             ("FC Vion Zlaté Moravce", 67),
             ("Komárno", 63),
             ("Petržalka", 61),
             ("FK Skalica", 60),
             ("Podbrezová", 65),
             ("Inter Bratislava", 59)]

SLO_TEAMS = [("Maribor", 85),
             ("Olimpija Ljubljana", 83),
             ("Celje", 78),
             ("Domžale", 75),
             ("Mura", 72),
             ("Koper", 77),
             ("Radomlje", 70),
             ("Tabor Sežana", 66),
             ("Bravo", 69),
             ("Krka", 64),
             ("Triglav Kranj", 62),
             ("Rudar Velenje", 65),
             ("Dob", 60),
             ("Aluminij Kidricevo", 61),
             ("Dekani", 58),
             ("Beltinci", 57)]

FIN_TEAMS = [("HJK Helsinki", 85),
             ("KuPS", 82),
             ("Inter Turku", 80),
             ("Ilves", 76),
             ("SJK Seinäjoki", 74),
             ("HIFK", 72),
             ("Honka", 70),
             ("Lahti", 69),
             ("KTP", 65),
             ("Mariehamn", 66),
             ("RoPS", 63),
             ("EIF", 61),
             ("Jaro", 60),
             ("TPS", 68),
             ("VPS Vaasa", 64),
             ("MP Mikkeli", 58)]

BIH_TEAMS = [("FK Sarajevo", 83),
             ("Željezničar", 81),
             ("Široki Brijeg", 78),
             ("Zrinjski Mostar", 80),
             ("Borac Banja Luka", 75),
             ("Velež Mostar", 74),
             ("Sloboda Tuzla", 72),
             ("Tuzla City", 70),
             ("Čelik Zenica", 67),
             ("Mladost Doboj Kakanj", 65),
             ("NK Travnik", 62),
             ("Radnik Bijeljina", 66),
             ("FK Krupa", 63),
             ("Igman Konjic", 61),
             ("Gosk Gabela", 59),
             ("FK Rudar Prijedor", 58)]
