# Countries

COUNTRIES = {
    "England": {"ucl": 4, "uel": 4, "uecl": 4},
    "Spain": {"ucl": 4, "uel": 4, "uecl": 4},
    "Germany": {"ucl": 4, "uel": 4, "uecl": 4},
    "Italy": {"ucl": 4, "uel": 4, "uecl": 4},
    "France": {"ucl": 4, "uel": 4, "uecl": 4},
    "Netherlands": {"ucl": 3, "uel": 3, "uecl": 3},
    "Portugal": {"ucl": 3, "uel": 3, "uecl": 3},
    "Belgium": {"ucl": 2, "uel": 2, "uecl": 2},
    "Scotland": {"ucl": 2, "uel": 2, "uecl": 2},
    "Austria": {"ucl": 2, "uel": 2, "uecl": 2},
}

DEFENSE_POSITIONS = ["GK", "LB", "RB", "CB", "WLB", "WRB"]
MIDFIELD_POSITIONS = ["LM", "RM", "CDM", "CM", "CAM"]
ATTACK_POSITIONS = ["LW", "RW", "ST"]

POSITIONS = DEFENSE_POSITIONS + MIDFIELD_POSITIONS + ATTACK_POSITIONS

# Teams
# Name
ENG_TEAMS = ["Arsenal",
             "Aston Villa",
             "Bournemouth",
             "Brentford",
             "Brighton",
             "Burnley",
             "Chelsea",
             "Crystal Palace",
             "Everton",
             "Fulham",
             "Liverpool",
             "Luton",
             "Manchester City",
             "Manchester United",
             "Newcastle United",
             "Nottingham Forest",
             "Sheffield United",
             "Tottenham Hotspur",
             "West Ham United",
             "Wolverhampton Wanderers"]

ESP_TEAMS = ["Alaves",
             "Almeria",
             "Athletic Bilbao",
             "Atletico Madrid",
             "Barcelona",
             "Cadiz",
             "Celta Vigo",
             "Getafe",
             "Girona",
             "Granada",
             "Las Palmas",
             "Mallorca",
             "Osasuna",
             "Rayo Vallecano",
             "Real Betis",
             "Real Madrid",
             "Real Sociedad",
             "Sevilla",
             "Valencia",
             "Villareal"]

GER_TEAMS = [("FC Augsburg", 70),
             ("Union Berlin", 80),
             ("VfL Bochum", 70),
             ("Werder Bremen", 70),
             ("Darmstadt 98", 65),
             ("Borussia Dortmund", 95),
             ("Eintracht Frankfurt", 85),
             ("SC Freiburg", 80),
             ("1. FC Heidenheim", 65),
             ("1899 Hoffenheim", 70),
             ("1. FC Koln", 70),
             ("RB Leipzig", 90),
             ("Bayer Leverkusen", 85),
             ("Mainz 05", 75),
             ("Borussia Monchengladbach", 75),
             ("Bayern Munchen", 100),
             ("VfB Stuttgart", 70),
             ("VfL Wolfsburg", 75)]

ITA_TEAMS = [("AC Milan", 90),
             ("AS Roma", 85),
             ("Atalanta", 85),
             ("Bologna", 75),
             ("Cagliari", 65),
             ("Empoli", 70),
             ("Fiorentina", 80),
             ("Frosinone", 65),
             ("Genoa", 65),
             ("Hellas Verona", 65),
             ("Inter Milan", 90),
             ("Juventus", 90),
             ("Lazio", 85),
             ("Lecce", 70),
             ("Monza", 75),
             ("Napoli", 90),
             ("Salernitana", 70),
             ("Sassuolo", 70),
             ("Torino", 75),
             ("Udinese", 70)]

FRA_TEAMS = [("Brest", 70),
             ("Clermont", 70),
             ("Le Havre", 65),
             ("RC Lens", 85),
             ("Lille", 80),
             ("Lorient", 70),
             ("Olympique Lyon", 80),
             ("Marseille", 80),
             ("AS Monaco", 80),
             ("Metz", 65),
             ("Montpellier", 70),
             ("Nantes", 70),
             ("Nice", 75),
             ("PSG", 100),
             ("Reims", 70),
             ("Rennes", 80),
             ("Strasbourg", 70),
             ("Toulouse", 70)]

NED_TEAMS = [("Ajax", 85),
             ("Almere City", 60),
             ("AZ", 75),
             ("Excelsior", 60),
             ("Feyenoord", 80),
             ("Fortuna Sittard", 65),
             ("Go Ahead Eagles", 65),
             ("SC Heerenveen", 70),
             ("Heracles Almelo", 60),
             ("NEC", 65),
             ("PEC Zwolle", 60),
             ("PSV Eindhoven", 80),
             ("RKC Waalwijk", 65),
             ("Sparta Rotterdam", 70),
             ("Twente", 75),
             ("Utrecht", 70),
             ("Vitesse", 65),
             ("Volendam", 60)
             ]

POR_TEAMS = [("Arouca", 70),
             ("Benfica", 85),
             ("Boavista", 70),
             ("Braga", 80),
             ("Casa Pia", 65),
             ("Chaves", 70),
             ("Estoril", 60),
             ("Estrela da Amadora", 60),
             ("Famalicao", 70),
             ("Farense", 60),
             ("Gil Vicente", 65),
             ("Moreirense", 60),
             ("Portimonense", 60),
             ("Porto", 85),
             ("Rio Ave", 65),
             ("Sporting CP", 80),
             ("Vitoria de Guimaraes", 75),
             ("Vizela", 65)
             ]

BEL_TEAMS = [("Anderlecht", 75),
             ("Antwerp", 75),
             ("Cercle Brugge", 70),
             ("Charleroi", 70),
             ("Club Brugge", 75),
             ("Eupen", 60),
             ("Genk", 80),
             ("Gent", 75),
             ("Kortrijk", 60),
             ("Mechelen", 60),
             ("OH Leuven", 65),
             ("RWD Molenbeek", 60),
             ("Sint-Truiden", 65),
             ("Standard Liege", 75),
             ("Union SG", 80),
             ("Westerlo", 70)]

SCO_TEAMS = [("Aberdeen", 75),
             ("Celtic", 80),
             ("Dundee", 60),
             ("Hearts", 70),
             ("Hibernian", 70),
             ("Kilmarnock", 60),
             ("Livingston", 65),
             ("Motherwell", 70),
             ("Rangers", 80),
             ("Ross County", 60),
             ("St Johnstone", 65),
             ("St Mirren", 65)]

AUS_TEAMS = [("Austria Klagenfurt", 65),
             ("Austria Lustenau", 65),
             ("Austria Wien", 70),
             ("Blau-WeiB Linz", 60),
             ("LASK", 70),
             ("Rapid Wien", 70),
             ("Red Bull Salzburg", 80),
             ("Rheindorf Altach", 60),
             ("Sturm Graz", 75),
             ("TSV Hartberg", 60),
             ("Wolfsberger AC", 65),
             ("WSG Tirol", 65)
             ]

# player_name, team_name, country_name, skill, main_position - can only have one, secondary_positions, tertiary_positions, age
PLAYERS = [
           ("Cole Palmer", "Chelsea", "England", 79, ["CAM"], ["RW", "CM", "RM"], ["LM", "LW"], 21),
           ("Reece James", "Chelsea", "England", 84, ["RB"], ["WBR", "CB"], ["CDM"], 24),
           ("Thiago Silva", "Chelsea", "Brazil", 85, ["CB"], [], ["CDM"], 39),
           ("Robert Sanchez", "Chelsea", "Spain", 79, ["GK"], [], [], 25),
           ("Ben Chilwell", "Chelsea", "England", 82, ["LB"], ["WBL"], ["LM"], 27),
           ("Levi Colwill", "Chelsea", "England", 75, ["CB"], ["LB"], [], 20),
           ("Moises Caicedo", "Chelsea", "Ecuador", 80, ["CDM"], ["CM"], ["RB"], 22),
           ("Enzo Fernandez", "Chelsea", "Argentina", 83, ["CM"], ["CDM"], ["CAM", "LM"], 22),
           ("Christopher Nkunku", "Chelsea", "France", 86, ["CAM"], ["ST", "CM"], ["LW", "RW"], 26),
           ("Raheem Sterling", "Chelsea", "England", 84, ["LW"], ["RW"], ["ST", "CAM", "LM", "RM"], 29),
           ("Mykhaylo Mudryk", "Chelsea", "Ukraine", 82, ["LW"], ["RW"], [], 23),

           ("Erling Haaland", "Manchester City", "Norway", 95, ["ST"], [], [], 21),
           ("Kevin De Bruyne", "Manchester City", "Belgium", 95, ["CAM"], ["CM"], ["LM", "RW"], 32),


           ("Alisson", "Liverpool", "Brazil", 90, ["GK"], [], [], 31),
           ("Andrew Robertson", "Liverpool", "Scotland", 86, ["LB"], ["WLB"], ["RB", "LM"], 29),
           ("Virgil van Dijk", "Liverpool", "Netherlands", 93, ["CB"], [], [], 32),
           ("Ibrahima Konate", "Liverpool", "France", 81, ["CB"], [], [], 24),
           ("Trent Alexander-Arnold", "Liverpool", "Brazil", 86, ["RB"], ["WRB", "CM", "CDM"], ["RM"], 25),
           ("Thiago", "Liverpool", "Spain", 84, ["CM"], ["CAM", "CDM"], ["LM"], 32),
           ("Dominik Szoboszlai", "Liverpool", "Hungary", 82, ["CM"], ["CAM", "LM", "RW", "LW"], ["RM"], 22),
           ("Alexis Mac Allister", "Liverpool", "Argentina", 82, ["CM"], ["CDM", "CAM"], ["LM", "ST"], 24),
           ("Diogo Jota", "Liverpool", "Portugal", 84, ["LW"], ["RW", "ST"], ["CAM"], 26),
           ("Mohamed Salah", "Liverpool", "Egypt", 93, ["RW"], ["LW", "ST"], ["CAM"], 31),
           ("Darwin Nunez", "Liverpool", "Uruguay", 82, ["ST"], ["LW"], ["CAM", "RW"], 24),

           ("Bukayo Saka", "Arsenal", "England", 87, ["RW"], ["LM", "RM", "LW"], ["WLB"], 22),
           ("Gabriel Martinelli", "Arsenal", "Brazil", 80, ["LW"], ["ST"], ["RW"], 22),


           ("Ansu Fati", "Brighton", "Spain", 79, ["LW"], ["ST"], ["CAM", "RW"], 21),

           ("Harry Maguire", "Manchester United", "England", 80, ["CB"], [], [], 30),
           ]